pipeline {

    agent any

    stages {

        stage("Docker Pull Image") {
            steps {
                script {
                    sh 'docker pull --platform=linux/x86_64 jonathanleedev/jenkify:latest'
                }
            }
        }

        stage("Docker Run Help") {
            steps {
                script {
                    sh 'docker run --rm jonathanleedev/jenkify:latest --help'
                }
            }
        }

        stage("Docker Run Example-Output Success") {
            steps {
                script {
                    sh 'docker run --rm jonathanleedev/jenkify:latest example-output'
                }
            }
        }

        stage("Docker Run wfapi Example Command") {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'jenkins-local-self-access', usernameVariable: 'JENKINS_USER', passwordVariable: 'JENKINS_TOKEN')]) {
                        sh 'docker run -e JENKINS_URL="https://8537-2001-bb6-7b45-7100-89ed-a80a-3a36-f686.ngrok-free.app" -e JENKINS_USER=${JENKINS_USER} -e JENKINS_TOKEN=${JENKINS_TOKEN} --network host --rm jonathanleedev/jenkify:latest get-run-count --job-name User_Input_Job'
                    }
                }
            }
        }

        stage("Docker Run Build Jobs YAML") {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'jenkins-local-self-access', usernameVariable: 'JENKINS_USER', passwordVariable: 'JENKINS_TOKEN')]) {
                        sh 'docker run -e JENKINS_URL="https://8537-2001-bb6-7b45-7100-89ed-a80a-3a36-f686.ngrok-free.app" -e JENKINS_USER=${JENKINS_USER} -e JENKINS_TOKEN=${JENKINS_TOKEN} -e POLL_RATE_SECONDS=10 --network host -v $(pwd)/sample:/tmp/sample --rm jonathanleedev/jenkify:latest start-build-jobs-yaml --build-jobs-yaml /tmp/sample/sample-builds.yaml'
                    }
                }
            }
        }

        stage("Docker Track Build Jobs YAML") {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'jenkins-local-self-access', usernameVariable: 'JENKINS_USER', passwordVariable: 'JENKINS_TOKEN')]) {
                        sh 'docker run -e JENKINS_URL="https://8537-2001-bb6-7b45-7100-89ed-a80a-3a36-f686.ngrok-free.app" -e JENKINS_USER=${JENKINS_USER} -e JENKINS_TOKEN=${JENKINS_TOKEN} -e POLL_RATE_SECONDS=10 --network host -v $(pwd)/sample:/tmp/sample --rm jonathanleedev/jenkify:latest track-build-jobs-status --build-jobs-tracking-yaml /tmp/sample/sample-builds-tracking.yaml'
                    }
                }
            }
        }

    }
}
